# Labeler labels incoming pull requests.
name: "Labeler"
"on":
- pull_request

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v6
      if: github.base_ref == null
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
